TIGRLab/datman

bin/qc-html.py
Fix for bug where last log entry repeats in the qc table
for bvec/bval differences and headers
=> Fix repeating bvec/bval and header diffs

bin/dm-qc-report.py
- Fixed bug where checklist entries were being written
for participants already in the list, causing duplicates
- Removed some lingering 'print' statements and replaced
them with appropriate logging
=> Fixed checklist bug and logging

bin/dm-proc-enigma.py, datman/proc.py
Still needs unit tests and refactoring, but it's working and uses config.py now.
=> proc-enigma is working again

bin/dm2-xnat-upload.py
I'm also writing unit tests for this part of the code, but it's taking a million years because there's so many dependencies and weird things to mock! So those will come later.
=> Bug fix: Resources not uploading with certain zip files.

bin/dm_link_shared_ids.py, bin/dm_xnat_project_overview.py, datman/utils.py
Added script to pull the downloadable spreadsheet from the XNAT gui MR Session tab. Also adds in some additional useful information like the date the scan was uploaded, the XNAT project it belongs to, and who uploaded the session. If a project has multiple XNAT projects, the spreadsheets are concatenated into one large one.
=> Added dm_xnat_project_overview

bin/dm-qc-report.py, bin/dm2-xnat-extract.py, datman/dashboard.py
Find technotes from repeat sessions, add repeat number to dashboard database.
=> Cope with repeat sessions

bin/dm2-xnat-extract.py
Checks to see if a backup already exists, deletes if yes, moves if not.
=> Bugfix: Improved error handling for resource backups

bin/dm-qc-report.py
I updated our hacky 'check for tech notes' set up to include MRP/MRC for SPINS.
=> Bug fix: SPINS MRP/MRC tech notes now being written to QC pages

bin/dm-link-project-scans.py, bin/dm2-link.py, bin/dm2-xnat-extract.py, bin/dm_link_shared_ids.py, datman/config.py, datman/utils.py
Most of the entry points for new scans/sessions should now detect a bad ID and avoid downloading/linking it.
=> Enforced ID validation

bin/dm-qc-report.py
Because images were only being added based on what shows up in
the 'expected files' table the split images werent being used.
These are now being found and used when a PDT2 tag is found.
=> Bug fix: PDT2 split images werent showing up on QC pages

bin/dm_qc_report.py, bin/track_scan_dates.py
Stand alone python program that prints a table showing latest upload information for a given study. Differentiates between _PHA, _PHA_ADN and, _PHA_FBN.
=> Trackscandates

bin/dm_proc_freesurfer.py, datman/config.py
proc_freesurfer: Modfied get_freesurfer_arguments to add expert.opts if need.
config: Modified get_subject_metadata to not add blacklist to qced_subjects.
=> Modified proc_freesurfer and config

bin/dm_qc_report.py, bin/nii_to_bids.py, bin/opt_to_bids.py
-  Will copy/convert nii files in OPT to BIDS format
=> Created opt_to_bids

bin/dm_qc_report.py
Probably why I should start using tests...
=> rewrite condition

bin/dm_proc_fmri.py
=> Add a task option so we don't have to run all tasks if only subset are relevant

bin/dm_proc_fmri.py
=> remove 1 word

bin/nii_to_bids.py
1. Runs in parallel
2. Explicit rewrite option
3. Maps scans to closest fmap
Only CMH fmaps implemented
=> nii_to_bids feature requests implemented

bin/nii_to_bids.py
Checking if session folder exists instead of just subject folder.
=> Rewrite fix

.github/auto_assign.yml, bin/dm_redcap_scan_completed.py, bin/dm_xnat_upload.py, datman/dashboard.py
Gabby noticed that one OPT participant had a REDCap record but the info wasn't being pulled. Moved functions to `dashboard.py` and added a commit.
=> Fix for some REDCap Scan Completed records not being pulled

bin/dm_bids_app.py, tests/test_dm_bids_app.py
we'll need to export the SBATCH_PARTITION environment variable when using slurm btw
=> Add slurm to dm_bids_app

bin/dm_to_bids.py
=> Updated hard-coded tags

assets/dm_bids_app_config/mriqc_local.json, assets/dm_bids_app_config/mriqc_scc.json, bin/dm_bids_app.py
The only real change is on lines 649 and 650. The rest is automatic formatting from atom.
=> Correct missing default_log variable

datman/utils.py
Kev updated the queue configuration so jobs can be sent to a default queue to allow overflow to work better.
=> Make jobs submit to default queue

bin/dm_redcap_scan_completed.py
redcap_scan_completed now  checks the specified variable REDCAP_STATUS for value REDCAP_STATUS_VALUE
(please merge config before this)
=> study by study control of redcap scan complete value

bin/dm_qc_report.py
=> Fix dm_qc_report crashing when displaying "missing" fields

bin/dm_qc_report.py, bin/dm_redcap_scan_completed.py, bin/dm_xnat_extract.py
- Stopped phantom QC jobs from crashing because I forgot to delete the 'chained' argument
- Stop dm_xnat_extract from crashing due to misnamed files (for realsies)
- RE: postgresql inserts crashing for dm_redcap_scan_completed, I deleted the duplicate record. Not sure how that got in there though, even though I spent a while investigating. So... I guess just keep an eye out for more of those.
=> Small bug fixes

bin/dm_redcap_scan_completed.py
=> Added exception for failed API request

bin/dm_redcap_scan_completed.py
decided to do a quick fix for now. it should make SENDEP redcap forms link to the dashboard properly, I unhardcoded the field for REDCap record_id.
=> fixing redcap linking so it works for SENDEP

bin/dm_proc_ea.py
we don't need to queue this job since the task parsing is pretty lightweight, the original script included computation on epitome outputs which needed job submission. 
Also excuse the commenting fix but just wanted to get this up and running asap :speak_no_evil:
=> ea task hotfix

bin/dm_header_checks.py
In response to Mike's comment in https://github.com/TIGRLab/admin/issues/1760
=> Added support for tolerances for fields that are lists

bin/dm_update_study_status.py, datman/config.py, datman/dashboard.py
based on the settings YAML key IsOpen. Fixed bug in config's get_key function where a value=False would cause the function to fail.
=> Added way to update study status in the dashboard 

bin/dm_task_files.py, datman/dashboard.py
dm_task_files.py finds the task files in the resources folders using a regex (that may be overridden in the config files with the 'task_regex' key) and links them to their own folder. It also adds them to the dashboard database if the dashboard is configured.
=> Add task file management script

bin/dm_qc_report.py, datman/dashboard.py
The auto-page regeneration wasnt working because batch mode didnt check for new sessions. I've added this in.
=> Updated dm_qc_report to notice new sessions when run in batch mode

bin/dm_header_checks.py, bin/dm_qc_report.py, bin/dm_xnat_extract.py, datman/header_checks.py, datman/scan.py
- Rearranged some code to make it accessible to the dashboard (without circular references)
- Updated dm_qc_report.py to try to use the dashboard database first for its header diff checks 
- Updated dm_xnat_extract to push the json sidecars into the scan table for use in header diff comparisons
=> Gold standards

bin/dm_parse_ea.py
The very messy version of dm_parse_ea that was used to parse EA task log files in early October 2019. This will be eventually updated to not be hardcoded and to actually use datman. but for now just committing this to datman from my https://github.com/gabiherman/parse_ea_task so it can be found centrally. It would probably be better suited for rigorous code review a little later down the line...
=> Add dm_parse_ea.py

datman/dashboard.py, datman/scanid.py, datman/utils.py
Can now get the entire study checklist/blacklist in bids format (use_bids flag) or individual entries by bids ID
=> Add ability to query checklist and blacklist with bids IDs

bin/dm_qc_report.py
Forgot to delete old function (thanks Jer for noticing)
=> Remove deleted dashboard function

datman/scanid.py, tests/test_datman_scanid.py
Added a basic bids file class to datman.scanid so I can more easily work with bids file names when finding / deleting files.
=> Added a bids file class to scanid

bin/dcm_to_nrrd.sh, bin/dm_link_shared_ids.py, bin/dm_qc_report.py, bin/dm_sftp.py, bin/dm_xnat_extract.py, datman/header_checks.py, datman/scan_list.py, datman/utils.py, datman/xnat.py
This should fix the remaining python3 issues. The scripts appear to run correctly from the command line now. Will keep an any out for any remaining issues though.
=> [FIX] Python3 conversion bug fixes (round 1)

datman/xnat.py
I _think_ this is the only this time.
=> [Fix] Python3 conversion bug fix (Round 3)

assets/bids/requirements.yaml
YAML structure giving ParserErrors, now fixed
=> [FIX] - BIDS requirements YAML

bin/dm_task_files.py
changed case of 'task_regex' to match config
=> fix to aggregate task files based on config

bin/dm_qc_report.py
=> DOC: Update ``dm_qc_report.py`` docstring with software versions

datman/dashboard.py
This updates references to a dashboard.queries function name changed in https://github.com/TIGRLab/datman-dashboard/pull/85 and should be merged at the same time.
=> [FIX] Update references to dashboard.queries function

bin/dm_parse_ea.py
This appends the Series number onto the task files so that .tsv outputs can be properly associated with their scans. Currently the default behavior means that files will overwrite each other in an indeterminate manner if there are multiple files for the same EA part. 
@DESm1th i think maybe with blacklisting it might be a good idea to also remove .tsv files?
=> ENH: Add --match-series option to enforce that matches Series# is found

docs/_static/css/custom.css, docs/conf.py, docs/datman_conf.rst, docs/datman_files.rst, docs/index.rst, docs/script_overview.rst
This contains some documentation that used to be on our documentation wiki. I've also added some config file values that hadnt been documented yet.
=> [Docs] Migrate contents from docs wiki + add missing config values

pyproject.toml
Belatedly update package dependencies based on dependabot suggestions
=> [DEP] Bump requests and urllib3 versions
