TIGRLab/datman

assets/blacklist-rm.sh
bin/qc-html.py
bin/xnat-extract.py

The new generated run scripts always set the --blacklist option for xnat-extract.py without checking if a blacklist.csv file exists, which may throw errors when xnat-extract.py tries to parse the table. The changes should handle this situation. 
The issues with xnat-extract.py failing to respect blacklists doesn't seem to be due to a bug, but is because some run.sh scripts don't set the blacklist option (for example the ANDT archive) so it's using the default of an empty list.

Blacklist issues

---

bin/dm-qc-report.py
bin/dm_proc_freesurfer.py
datman/fs_log_scraper.py
tests/test_dm-qc-report.py
tests/test_dm2-xnat-upload.py
tests/test_fs_log_scraper.py

Removed/updated + added some tests. 
Added proc_freesurfer upgrades:
- Scrapes the freesurfer output logs to check for differences in how each subject was run
- Able to take T2s and Flairs as additional input niftis
- Able to resubmit all timed out subjects by setting a single flag
- Able to log to a remote log server
- Can use FS 6's parallel flag to run each job in parallel
- Switched to qbatch, so all freesurfer job logs are stored in one directory
Small change to qc-report's code that checks for repeat sessions to ensure the script still runs for installations that don't have a dashboard set up.

Updated tests, made proc_freesurfer FS 6 compatible and added log scraping

---

bin/dm2-link-sprl.py

If an error is generated by any session, logs it and continues.

Made processing more robust

---

datman/utils.py

Commnd line escaping was causing dcm2mnc to fail as it requires
shell expansion. Changed generic shell quoting (wrapped arguments
in single quotes using pipes.quote) to single character quoting
str.replace(';','\\;')

Bugfix: minc file exports

---

datman/config.py
datman/scan.py

Config.py had quietly been mapping all 'DTI' tags to DTI3T since config.py was written. I fixed the bug last week but now other things started failing due to map_xnat_archive_to_project allowing things to be mapped only by the study ID and not being able to resolve it for DTI without a site ID as well.

Bug fix: DTI configuration resolution

---

bin/dm_proc_split_pdt2.py

Some files are labeled PDT2 but only contain a T2. These files will now get a link tagged with 'T2' pointing to the original PDT2 to make it explicit.

PDT2 single volume bug fix

---

bin/dm_proc_fmri.py
bin/dm_proc_freesurfer.py
bin/dm_qc_report.py
bin/dm_xnat_extract.py
datman/scan.py

Changes:
- Removes the redundant list of tags in dm_qc_report's handlers.
- Cleans up some direct accesses to the configuration dictionaries (bad practice)
- Removes some no longer used code
- Fixes two old, easily missed bugs. Namely that underscores in the file path caused dm_qc_report to fail to identify the resources and exit with an error and that referencing an undefined study code caused a name error crash due to an undeclared reference to 'logger' inside datman/scan.py

Cleaned up tag configuration access and redundant tags

---

datman/config.py

Sites with multiple scanners in config file return duplicate project IDs

Fix for sites with multiple scanners

---

bin/dm_proc_fmri.py

Make it easier for people wanting to run custom pipelines to output into their own folders with additional options to override config.

Add export and output options to dm_proc_fmri

---

bin/dm_link.py
bin/dm_link_project_scans.py

When a src target had multiple sessions, the target session ended up with links for all scans in all sessions. This PR fixes this for https://github.com/TIGRLab/admin/issues/1622

Fixed links to wrong session

---

bin/dm_qc_report.py

adds an extra parameter to run_header_qc so it can access site config and scan type
don't pull until qcmon is updated AND bvecs and bvals have been added to study gold standards

 Calls updated qcmon qc-headers

---

bin/dm_log_server.py
datman/dashboard.py

The uncaught exception was tanking dm_xnat_extract when it tried to pull down studies that didnt yet have at least one QCer assigned in the database. Whoops.

Bug fix to stop killing dm_xnat_extract

---

bin/dm_bids_app.py
bin/dm_header_checks.py
bin/dm_link_shared_ids.py
bin/dm_proc_dtiprep.py
bin/dm_proc_freesurfer.py
bin/dm_proc_maget_brain.py
bin/dm_qc_report.py
bin/dm_redcap_scan_completed.py
bin/dm_sftp.py
bin/dm_to_bids.py
bin/dm_xnat_upload.py
bin/xnat_fetch_sessions.py
datman/config.py
datman/xnat.py

Before pulling into the archive we need to:
- Add  timepoints.header_diffs to the production database
- Add a list of header fields to ignore to tigrlab_config.yaml under the key 'IgnoreHeaderFields'
- Add a dictionary of header fields and their tolerances to tigrlab_config.yaml under 'HeaderFieldTolerance'.  
Still working on the dashboard UI changes to actually use this info, but the QC pages will work as before (I cleaned up the table that presents diffs a bit)

Json standards

---

bin/dm_header_checks.py

type(bool obj) != bool_
always evaluates to True under most circumstances

bool_ --> bool in dm_header_checks

---

bin/dm_header_checks.py

Some subjects didnt have a qc report because isclose complains about lists with different lengths

Fixed exception when series / standard have different length

---

assets/dm_bids_app_config/mriqc_local.json

temporary fix so low-moby isn't used, since we'll be replacing everything with nextflow pipelines down the line...

mriqc should run on high-moby

---

datman/scanid.py

Changes are done to make it easier to structure BIDS filename construction since the sub component is the field not the ID

BIDS subject ID should not include sub- field 

---

bin/dm_header_checks.py
bin/dm_qc_report.py
bin/dm_xnat_extract.py
datman/header_checks.py
datman/scan.py

If dcm2niix complains about possibly missing images a text file with the error message gets made and the message gets pushed to the database for later display by the dashboard. This pull request depends on my other one RE: gold standards, so most of the changes can be ignored (sorry)

Add dcm2niix errors to database / file system

---

bin/dm_qc_report.py
bin/dm_symlink_scans.py
bin/dm_xnat_extract.py
datman/exceptions.py
datman/xnat.py

This pull request:
1. Stops dm_symlink_scans from complaining when it looks for dicoms and they're missing because they were blacklisted.
2. Fixes the bug I accidentally introduced where dm_qc_report.py would crash when a json was missing or the gold standard wasnt found. The code for generating header diffs with the dashboard now behaves the same as the code for doing it from the file system.
3. Refactors dm_xnat_extract.py a bit to improve readability
4. Fixes a bug in dm_xnat_extract.py where some scans (definitely multi-echo scans but possibly others) werent having jsons added when they got exported because they didnt have a scan entry in the database in time for the call to 'update_side_cars'

Moar patches! (and some refactoring)

---

bin/dm_redcap_scan_completed.py

Sometimes, when pulling from REDCAP, python interprets the content as bytestring rather than string. The database doesn't decode this automatically resulting in errors due to character length. This has been an issue for SENDEP for which redcap records have never pulled in correctly because the redcap_version was always read in as a bytestring
Run a decode to UTF-8 on the redcap version

[FIX] - Decode bytestring for version from redcap

---

bin/dm_qc_report.py

This fixes two dm_qc_report.py issues:
1. When the tag and series description are identical the file name is mangled in a way that stops header diffs from being found
2. When a scan name can't be found in the header diffs the entire report fails to generate

[FIX] dm_qc_report.py header diff related crashes

---

bin/dm_link_shared_ids.py
setup.cfg
tests/test_datman_scanid.py
tests/test_dm_qc_report.py
tests/test_dm_xnat_upload.py
tests/test_fs_log_scraper.py
tests/test_scan.py
tests/test_utils.py
tests/test_xnat.py

- All nose dependencies have been removed in favour of pytests
- Fixed bug in test_dm_xnat_upload where test was passing unconditionally 
- Minor added change where dm_link_shared_ids now imports using the base package directory for dm_link_project_scans

[MAINT/FIX] - Remove nose dependency, fix issues with some tests

---

bin/dm_blacklist_rm.py
bin/dm_link_shared_ids.py
bin/dm_xnat_upload.py
datman/scan_list.py
datman/utils.py

No one seems to care about the multiple UUIDs so I've made that quieter, and I've allowed dm_blacklist_rm to delete blacklisted scans even if the entire session hasn't finished being signed off.

[REF] Clean up error messages

---

.circleci/config.yml

Since **Master** will be our in-house production branch which is always being tweaked, we want to reserve deployment for milestones/major bug fixes.
Any commit/PR pushed to the branch **release** will be deployed to pypi.

[FIX/MAINT] - Only deploy on pypi when commits/PRs are made to the release branch

---

bin/dm_link.py
bin/dm_link_project_scans.py
bin/dm_xnat_extract.py
bin/dm_xnat_upload.py
bin/xnat_fetch_sessions.py
datman/exceptions.py
datman/fs_log_scraper.py
datman/scanid.py
datman/utils.py
datman/xnat.py
tests/test_datman_scanid.py
tests/test_dm_xnat_upload.py
tests/test_utils.py

This updates our core scripts that interact with XNAT (and dm_link) to allow zip files and xnat experiments to use the KCNI conventions. 
Note: I did **NOT** yet update dm_link_shared_ids.py, dm_xnat_project_overview.py, or track_scan_dates.py. The first needs a major overhaul (it still doesnt allow SENDEP linking to work right, and predates the dashboard) that I'd like to spend more time on and none of the three will be affected yet by our initial KCNI XNAT test cases. But I'll push that later since we need to move forward.
For studies and sites that we want to start migrating we'll have to update the settings file to add:
XNAT_CONVENTION: KCNI
and for study / site fields that need to be changed for KCNI we'll have to add an id map that matches this format:
ID_MAP:
STUDY: {KCNI_STUDY: …

[ENH] Add KCNI ID support

---

.gitignore
datman/header_checks.py
tests/test_header_checks.py

Issue occurs because ValueError returns a Python False which isn't of type np.bool_(False).

[FIX] - Bug when SliceTiming length's don't match gold standard

---

bin/dm_xnat_extract.py
bin/xnat_fetch_sessions.py
datman/scanid.py
tests/test_datman_scanid.py

This fixes a problem where scan tags with the substring "PHA" were being flagged as invalid, and adds tests to catch this and other similar tag issues, and also reverts some of the changes made to xnat_fetch_sessions because I forgot that their server's experiments are not meaningful and it isn't really necessary to get them to switch to KCNI format.

[FIX] Bug fixes from adding KCNI name support

---

bin/dm_xnat_extract.py
bin/dm_xnat_upload.py
datman/config.py
datman/exceptions.py
datman/scanid.py
datman/xnat.py
tests/test_datman_scanid.py
tests/test_dm_xnat_upload.py

I forgot to update dm_xnat_upload and dm_xnat_extract to allow multiple xnat servers to be used for one study :( This fixes this oversight.

[REF] Allow multiple XNAT servers to be used for upload / extraction

---

datman/dashboard.py

The dashboard blueprints refactor in https://github.com/TIGRLab/dashboard/pull/61 means datman needs to operate within an app context. This just makes sure that happens on import. It should be merged in when the blueprints PR is.

[FIX] Ensure database is available for datman

---

bin/dm_xnat_upload.py

This fixes:
1. Crashes when uploading zip files with only resource files and 0 dicoms
2. Crashes from a log message that gets emitted when upload fails for other reasons

[FIX] missed edge cases in dm_xnat_upload

---

bin/bidsify.py
tests/test_bidsify.py

In bin/bidsify.py I just added a check to see if dataset_description.json exists, then don't re-write it if it does.
I also wrote a quick unittest for this for this addition.

Bidsify fix - don't re-write dataset_description.json on every run

---

.circleci/config.yml

I created a new [GitHub account](https://github.com/tigrlab-bot) with an SSH key so CircleCI can update the `gh-pages` branch automatically. I tried using clevisboxx but the login and email confirmation gets sent to either Joe or Jon's CAMH email.

MAINT: update ssh key for auto-deploying docs

---

bin/dm_xnat_extract.py
datman/scanid.py
tests/test_datman_scanid.py

To change the subject ID field of an ID add something formatted like the below example to the ID_MAP in a study's settings
```yml
ID_MAP:
SUBJECT:
'kcni_regex->replacement_str': 'dm_regex->replacement_str'
```

[ENH] Allow the subid field to be modified between naming conventions

---

bin/dm_link_shared_ids.py
tests/test_dm_link_shared_ids.py

We havent used the XNAT integration for linked IDs since the dashboard was made, and now that we're moving studies to the KCNI server it is causing crashes so I've removed it.

[FIX] Removed XNAT integration (was unused)

---

assets/bids/requirements.yaml
bin/bidsify.py

- Can now have multiple fmap types determined by the (modality, acq) tuple. These will be independently matched to scans
- "inherit" spec under "alt" implemented allowing source files to augment the bids fields of their derived children
- Fixed case where if the derivative of a file is under a different class, then the destination directory needs to be updated
- When derivatives were specified they were selected in lieu of the parent scan. The update now allows you to specify derivatives in addition to the parent by simply specifying the derivative to have a type that is the parent's type. This means you can have the parent in addition to its derivative pushed into the BIDS directory instead of just the latter. (Useful for boldref/sbref cases)
- `is_ref` option added which denotes that …

[ENH] - Remove single fmap-type assumption for BIDSIFY, more flexible derivative specification

---

bin/dm_redcap_scan_completed.py

Needed to handle function signature changes from https://github.com/TIGRLab/dashboard/pull/67

[FIX] update add_redcap function call

---

.circleci/config.yml
bin/bidsify.py
setup.cfg

This is a bugfix for the bidsify BIDS conversion script.
The way that bidsify works is by reading in assumptions for how fmaps should be matched within the datman config file using the `pair` key within the config yaml. However bidsify provides erroneous outputs when:
I.e, the OPT dwi dir-AP TOPUP requires a pair (dir-PA), however for UT1 it does not - the b0 acts as the pair. However the OPTIMUM scanning sequence is such that the next fmap is a dir-PA meant for the faces task. As a result, bidsify erroneously pairs the dwi-AP topup with the fmri-PA topup. 
The fix is to include the `intendedfor` key in the matching protocol so we don't accidentally match dwi topup to func topup
In addition, the script has been updated to rely more on site-specific configuration if needed. Meaning if we …

[FIX] - fix bidsify match algorithm associating the wrong fieldmaps

---

bin/dm_xnat_extract.py
datman/xnat.py

TAY01 ASL scans weren't being pulled down because they didnt have an 'image_type' and were being assumed to be derived scans. This swaps the order of the checks so that we only check if something is derived if it matches a tag, and changes the default behavior to assume that those without image_types are **not** derived.

[FIX] Update how derived scans are handled

---

bin/dm_parse_faces.py

Fixed up PEP8 issues and added a bit more clarity to logging

[ENH] Add dm_parse_faces

---

bin/dm_redcap_scan_completed.py
tests/test_dm_redcap_scan_completed.py

When pulling redcap records from SPN30/31 constant 'duplicate record' exceptions were happening because SPN31 config causes the SPN30_CMH IDs to be read as SPN30_CMP and the script attempts to readd the record. This will stop the bad ID conversions from happening so records can be added correctly.

Added fix for SPN30/31 redcap issues

---

datman/scan.py
tests/test_scan.py

Also removed tests that relied on dcm properties
Also taking this approach should we go ahead and remove all extraneous path specs (i.e nrrd/mnc?)

[FIX] Scan module fails trying to set dcm properties

---

.circleci/config.yml
docs/requirements.txt
setup.cfg
tests/test_dm_qc_report.py
tests/test_scan.py

This fixes:
- An out of date datman test
- An issue with sphinx/docutils failing to build valid docs
- A call to checksum a file that hadnt yet been checked out that was causing errors

[FIX] Deal with circleci errors

---

bin/dm_deface.py

Added a script to perform defacing.
I'm looking for some suggestions on better implementation with datman and the dashboard:
- Should `--suffix-id` come from the study config?
- I ended up saving the pydeface command to the json file. Not sure if we should overwrite the original scan. My initial preference is to keep both files. It could be good to use both to create a mask overlay QC image and then if we want, we can replace the original image after QC

ENH: Add defacing script

---

bin/dm_xnat_extract.py

This is my base work for getting xnat_to_bids working on our system. This adds the function `xnat_to_bids` that pulls the data directly from xnat into a tmp folder, and then dcm2bids is run on that tmp folder with an appropriate json for that study. This is called instead of the usual xnat to nii pull if you call `dm_xnat_extract.py` with the tag `--use-dcm2bids`. Several arguments for dcm2bids are also allowed to be controlled (like `--dcm-config`, `--forceDcm2niix`, and `--clobber`). 
I would greatly appreciate feedback on this! Right now I have some design decisions that I'm unsure of as well:
- The default dcm2bids json location for each study is at `/archive/data/$STUDY/metadata/dcm2bids.json`. I think this might be a good idea instead of forcing it into the yamls for each of the …

Added inital xnat_to_bids function and error checking for it

---

bin/dm_xnat_extract.py

Quick fix for wrapping dcm2bids import in an exception in case the user does not want to import it for using regular dm_xnat_extract, or is not able to find it while using the `--use-dcm2bids` flag. 
In the future I will look into adding a more graceful approach such as [the current dashboard imports](https://github.com/TIGRLab/datman/blob/master/datman/dashboard.py#L21) but this is just a quick fix for now.

Wrapped dcm2bids import in exception message for better messaging

---

bin/dm_parse_faces.py

Before the break I realized that there was a bug in the FACES parser that was resulting in output tsvs not being saved in the correct nii/<SUBJECT> directories. Also a few of the OPT session .txt files had UTF-16 encoding issues wherein the files were not being decoded properly due to a missing BOM, so I added some code to try specifying endianness which resolves most issues.

Updates and bug fixes for dm_parse_faces

---

.circleci/config.yml

16.04's image is being phased out. This updates our config to use 20.04 instead and updates the python version to 3.9

[FIX] Update circle ci ubuntu + python versions

---

docs/requirements.txt

Have to explicitly pin docutils below version 0.18.0 or the circleci build_docs step fails

[FIX] Docs build failures

---

bin/dm_parse_ea.py

Ran into a special case where there was a "Quit" code at the end of the EA task file with `nan` entries causing a bunch of type errors. Fix is to remove the index associated with "Quit".
1. Refactor to remove code duplication: ce60dc3a05db6d51d551c56012018ac9c2d07fdf
2. Add check to handle quit signal: c46048b43d255624acf82eeb5ffd1b293f503f77, 407a06d68a6701ec7d23b135ade6b7a491e667c1
3. Apply code formatting and display error message on exception: 1e81ac4166f5e441d26e35c9ba59876a3e192684

FIX: Fix/ea handle quit code

---

bin/dm_xnat_extract.py

Small fix with behavior of `xnat_to_bids`: Before it would download the zip from xnat before checking if the subject was already converted to bids in the destination folder, which would add unnecessary time to batch runs. Now it will check the destination folder for the subject before attempting to pull their data (unless the --clobber tag is used of course)
I'm also working on a doc page to illustrate how to use `xnat_to_bids`, but with this fix we can safely put `dm_xnat_extract.py $STUDY --use-dcm2bids` in nightly scripts as it will skip over converted subjects properly.

[FIX] Fixed xnat_to_bids ignoring --clobber before pulling data

---

bin/bidsify.py

Previously bidsify was using just the series number but this is an incorrect assumption when repeats are included. This fix adds a filter to the list of potential candidate scans by additionally matching on the session number.

FIX: Handle sessions (repeats) appropriately in matching algorithm

---

bin/dm_qc_report.py
datman/dashboard.py
datman/metrics.py

After the move to the new dynamic QC pages tons of QC jobs were submitted to generate metrics that were (for some reason) missing from the QC folders. This large number of jobs consumed all available database connections. This was because SQLAlchemy opens a transaction whenever database reads happen and doesn't close them until the next commit/rollback. dm_qc_report was reading some values from the database prior to generating metrics, which left connections open 'idle in transaction' for 30+ minutes while the metrics were created.
This PR:
- Adds a decorator that will ensure a transaction ends after a function it wraps exits (8e248ce455b2a2832fa3d58fbcb763e39a92351f)
- Refactors dm_qc_report a bit to ensure all transactions are closed before metric generation happens …

[FIX] qc_report consuming all db connections + queue jobs timing out

---

bin/dm_qc_report.py
datman/metrics.py
tests/test_metrics.py

This PR addresses three bugs in dm_qc_report.py
- Phantoms with anat data were resubmitting to the queue every night, because their manifest file contained only an empty dict, leading to the file write being skipped. This led these phantoms to appear as though they had not completely generated. (2861e755275e0f413c4730e098839d32ea7160aa)
- Scan lengths were not being added to the database because a relative path was being given to update_dashboard and the files couldnt be found. The error was also being missed in the logs, because the log level was debug. (0e195e3f6c901c8f236afd00ef12352a86173b8a)
- Header diffs werent updating when a new gold standard is found, because the new standard was not being provided to the function call. This led to some sessions appearing as though they had not …

[FIX] address dm_qc_report edge case + db update issues

---

datman/xnat.py
tests/test_xnat.py

This enables users to use the `XnatType` key in lieu of `SeriesDescription` within a study's `ExportInfo`. The result is that tag identification will happen using XNAT's `Type` data field.
The justification behind using this feature is that XNAT's `Type` data-field is editable whereas SeriesDescription is not. As a result XNAT Project owners/maintainers can override the SeriesDescription if the original SeriesDescription doesn't properly allow us to identify an appropriate Tag.
Also this is a my bad moment but I habitually run yapf when saving code and it formatted a bunch of irrelevant lines.... For the actual changes made look at:
1. The chunk at L1565 in xnat.py
2. The chunk at L187 in tests/test_xnat.py

ENH: Enable XnatType key in ExportInfo

---

.github/workflows/assign-reviewers.yml
.github/workflows/label-pr.yml
.github/workflows/run-tests.yml

This should fix the previous job failures without introducing security issues. I can't tell if the run-tests permissions are sufficiently permissive until this PR is merged, since the github token permissions wont update until post-merge, but it should only need pull request write permission.

[FIX] Adjust pipeline permissions to stop jobs from failing

---

assets/config_templates/main_config.yml
bin/dm_blacklist_rm.py
docs/datman_conf.rst

This updates dm_blacklist_rm to use a config value (BlacklistRm) or command line arg (--path) to override the default list of paths to purge blacklisted files from.

[ENH] un-hardcode dm_blacklist_rm's list of directories to purge from

---

datman/exporters.py
datman/scanid.py
datman/xnat.py
tests/test_datman_scanid.py

- 5cfb6a0c6f13be72fb0b8baa22c210a4c6360bbe Allow the 'dir' attribute to be set for func bids file names (CLZ uses dir-AP/PA with rest)
- b3fc9c0bfc6591d68ed606c741bd7b52243b575b Stop a filename parsing error from crashing export for an entire session. 
- de5f811efc0e82d7687ecfd158aa73b7e69e30f6 Catch the correct exception when no XnatPort has been provided

[FIX] Stop nightly run log issues

---

bin/dm_redcap_scan_completed.py
datman/exporters.py

- Stop redcap subid fields from raising exceptions when the user left whitespace after the ID (b71bc0defb7e98eadee62eaef9acc61686abbbcf)
- Stop linked scans from being left out of the database when datman.xnat.XNATExperiment can't name them correctly (e.g. CBF files for TAY) (ce66ddecb07229585423a65b4b211033bfd36811)

[FIX] Fix REDCAP ID issue + linked scans missed by datman.exporters.DBExporter

---

datman/exporters.py

Currently BidsExporter is not properly detecting when a repeat session comes in. This updates BidsExporter.export() to add the repeat numbers to the json side cars and to run dcm2bids with force-dcm2niix when the session is a repeat. It also updates BidsExporter.outputs_exist() to take into account these repeat numbers when deciding if all outputs have been created.

[FIX] Update xnat extract bids conversion to better handle repeat sessions

---

datman/exporters.py
datman/utils.py

This depends on https://github.com/TIGRLab/datman/pull/350. Previously, because there was no way to tell which repeat a particular scan in the bids folder belonged to, scans in the bids folder were being mislinked as belonging to all repeat/sessions that existed for a timepoint. This fixes this by using the side car contents, which https://github.com/TIGRLab/datman/pull/350 updates to contain the correct repeat number.

[FIX] update xnat_extract NiiLink to stop repeats from being linked under multiple session numbers

---

datman/exporters.py

PREDICTS uncovered a bug with tech notes not being detected / added to the dashboard if they're downloaded after the rest of the scan data has already arrived. Added a check to 'DBExporter.outputs_exist()' to ensure the database gets updated.

[FIX] Ensure tech notes are pushed if they arrive after scan data

---

assets/config_templates/main_config.yml
bin/dm_redcap_scan_completed.py
docs/datman_conf.rst

Previously I tried to remove the RedcapApi setting because it was super redundant and created confusion, but recently this has started causing trouble with predicts. SO. I've put it back in under the name 'RedcapApiUrl' and updated our documentation in a way that will hopefully be clear, while also allowing plain-old RedcapUrl to be used when there are no differences in the URL.

[FIX] Update API URL retrieval, and documentation for the config val

---

bin/dm_xnat_extract.py
datman/exporters.py
datman/xnat.py

Recently we've noticed that xnat downloads of some dicom series were failing sporadically. Then, dcm2bids was exporting from the incompletely downloaded data. Our code was then seeing the bids folder for the session and skipping it for future re-extraction attempts causing the data to be missing from the archive until an RA notices and points it out to us.
This fixes this situation by:
1. Increasing the starting timeout duration for downloads
2. Fixing a bug that was making our code susceptible to 404 errors after our xnat session timed out
3. Adding error files to the nii folder when NiiLinkExporter is used, so the missing scans can be reported in the dashboard
4. Adding a mode to dm_xnat_extract to re-extract using the tmp folder for situations when the bids config changes (unrelated to …

[FIX] Stop series download from failing silently

---

datman/exporters.py

This PR stops a bug that causes error messages to be left behind in the database even after they've been resolved.

[FIX] Remove conversion error message from DB when no longer exists

---

bin/dm_redcap_scan_completed.py
bin/dm_xnat_extract.py
datman/exporters.py
datman/scan.py
datman/xnat.py

- Add a function to detect a shared XNAT experiment (46468149daffab9ec2b778466b86fd8a35815410)
- Add a `datman.exporters.SharedExporter` class that finds and symlinks relevant files (i.e. those with the correctly configured tags) from the XNAT source session (b642855c3bdb844403baab8bb4a619eeb2a66c2a, 9584af84addc5e2d50ed5c1ee1f30417a82e4469, 85b3d015d881e493b5b5d73a60b228877a96895e, b61671fb3e61ee27c47de118da455f3f8e446bf6, d45703cc6e38b048bb031320494758d447cfead0)
- Update `datman.exporters.DBExporter` to mark shared scans with the correct source scan ID (7f8f8a7da36cd7eaf8f7392addde3858d44caa9f)
- Fix `datman.exporters.DBExporter` bugs related to some scans missing on the first run of `datman/bin/dm_xnat_extract.py` when those scans first export only to bids (instead of the legacy nii …

[ENH] Allow datman to handle linked XNAT sessions

---

bin/dm_link.py
bin/dm_redcap_scan_completed.py
bin/dm_task_files.py
datman/xnat.py

This PR:
- Adds a clearer error message when the XNAT server returns an empty file [`datman/xnat.py`, 01ca591de2786cd9a294161523968d77e249d253]
- Adds a message that's more useful for debugging when a zip file's intended ID is already in use by another file [`bin/dm_link.py`, 5a112678b2eb82bde6434b69b2a91fa53bca4bbf]
- Prevents task files from being named with unparseable characters (which can break scripts that use the task files) [`bin/dm_task_files.py`, 01bd074dcef9dfa51ff95b60c6c8aea140f516eb]
- Allows redcap record IDs matching a regex to be ignored, helping to limit noise when unneeded records may be in the same project [`bin/dm_redcap_scan_completed.py`, 230d2495afd0431ca85520f4fced008b5851d2d6]

[ENH] Add better error messages + filter out noisy redcap messages

---

datman/utils.py
tests/test_utils.py

This updates `datman/utils.py`'s `find_tech_notes` to be able to find non-pdf tech notes, without grabbing unrelated files.  It also adds some test cases that would have caught the original problem(s) :)

[FIX] Find non-pdf tech notes

---

assets/config_templates/main_config.yml
bin/dm_link_shared_ids.py
datman/xnat.py
docs/datman_conf.rst
tests/test_dm_link_shared_ids.py

This pull request:
- Adds functions to datman.xnat.xnat to share subjects and experiments (48471bfb9ffc2bfa0580cda26545d944fbacea3d)
- Allows dm_link_shared_ids.py to use non-standard (i.e. non-'redcap_scan_completed') field names (1610882c5d42a5990d5b8d859e43a93a8467e4f2)
- Adds documentation for two new settings (`RedcapSharedIdPrefix` and `XnatDataSharing`) (b738b37224da69581c2b8847bd46ce7348752296)
- Adds xnat sharing to dm_link_shared_ids when `XnatDataSharing` is configured. (4bc5cf1a5a3ac1678cdd2a9ff022bc63fe8f9a62)

[ENH] Auto-share XNAT sessions based on REDCap contents

---

bin/dm_link.py
bin/dm_link_shared_ids.py
bin/dm_redcap_scan_completed.py
bin/dm_xnat_extract.py
datman/xnat.py

This pull request
- Adds small reminders of how to fix errors to some log messages (a5fd143b59f8a68530fe8b53641725a60e5554fa, 98f9cd58ce706d5ebd2c1bb20dd7df20ab153d92, 0e712fc51275b6cc5957f2a3e09120fc0be289c6)
- Ensures the correct list of tags are used when sessions are shared (af0161f9978624bfe7cff7f662974a0e48e1fb7b)
- Ensures immediate exception happens when xnat login has failed due to expired password (instead of later on when the connection actually gets used) (31bc14257838857270f8aec84a479b8c499da13b)

[FIX] Add small bug fixes + log message improvements

---

bin/dm_qc_report.py
datman/metrics.py

This PR fixes:
- A `dm_qc_report.py` doc string error telling users to load `MATLAB` instead of our actual module `matlab` (76634df517a7aaf0e27e7105afad64a77555e3ec)
- A function name typo that caused crashes when running `dm_qc_report.py` with the `--remake` flag (5a7d378ebc83ab627f76e5677239bc38611983e4)
- A recurring issue with `dm_qc_report.py` queue jobs timing out for very large scans (59f882c6543b3fd53c5fa46ea022e186c1540d9e)
- A bug that stopped regeneration of existing QC files when running `dm_qc_report.py` with the `--remake` flag (3f6a409881cfabf7dc85798fc6451b138b4feb2e, bfadd08faef872e4f2a0a7ad39acf1cac97644ae)
This PR adds:
- A `--refresh` flag so that header differences (and scan lengths) can be forced to be recalculated without having to delete existing files or waiting …

[ENH] Add --refresh flag to dm_qc_report

---

bin/dm_xnat_extract.py
datman/exporters.py

This PR contains a variety of bug fixes that fell through the cracks as a result of my head injury at the end of 2023 (ugh).
- [9279812a28b166a118ab4d3d6db6da548dc6b424] Pass the correct log level to dcm2bids
- [4cde97a54a78ca8b47d77234863bb640f293267d] XNAT series numbers sometimes end up with a string appended when a merge goes wrong and series numbers get duplicated (this is an error that must be addressed within XNAT when it occurs). This fix stops these malformed series numbers from crashing the entire run of dm_xnat_extract.py
- [3fa8c3e9fe095cc29f4595c2d36fc0633cf37fd8] This fix stops a single exporter from crashing an entire run of dm_xnat_extract when an exception is raised.
- [56346353a0e9003aa817cc22c47f9d3934700765, 734129637a885944780386bb0640f008f23051b7, …

[FIX] Add bug fixes that never got committed to main

---

assets/config_templates/main_config.yml
bin/dm_blacklist_rm.py
datman/exporters.py
datman/scan.py
docs/datman_conf.rst

This PR updates our dm_blacklist_rm script and the scans + exporters to allow blacklisted files to be stored in a 'blacklisted' sub dir instead of being deleted from the filesystem completely. It also allows the script to work properly in the bids folder.

[ENH] Keep blacklisted files + handle blacklisted files in bids folder
